/*
 * Copyright 2020 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
module.exports = [
  /%([^0-9A-Fa-f]($|[^0-9A-Fa-f])|[0-9A-Fa-f][^0-9A-Fa-f])/,
  /_debugbar/,
  /.+\.axd/,
  /.+\.log$/,
  /(?!\/\.(well-known|rum))\/\./,
  /(Homestead|circle|_?config)\.ya?ml$/,
  /[()'"]/, // braces and escapes
  /[Tt]hank.*\.txt$/,
  /\.\./, // do not go a directory up
  /\.gitignore/,
  /\.htaccess/,
  /\.htpasswd/,
  /\.html%.+/,
  /^[^?]+\.($|\?)/, // file name ends with a dot
  /\.swf$/,
  /\/_?debug/,
  /\/(.?php.*|tiki.*|test.*|user.*|wp-|ws|t.*|v.*|u.*|wiz.*|[Ww]eb)([aA]dmin|wiz.*)/,
  /\/(bower|config|\.[-_\w]+|app|\w+404)\.json/, // a bunch of json files, leftover from development
  /\/(plugins?)\/.*(servlet|metrics)/,
  /\/(solr|jira|confluence|jenkins|servicedesk|app)\/.*(config|plugins|user|kibana)/,
  /\/[Ww][Ss]_/,
  /\/[Ww]ord[Pp]ress|\/WebSphere|\/wwwroot/,
  /\/@/,
  /\/\??%2[AaEe]/, // escaped . and *
  /\/\.\./,
  /\/\.env/,
  /\/\//, // double slashes
  /\/\/etc\//,
  /\/\$%7[bB]/,
  /\/%24%7[bB]/,
  /\/%252e/,
  /\/%C2%B0/,
  /\/App_Data\//,
  /\/autoconfig/,
  /\/cloudfoundryapplication/,
  /\/CVS\/Entries/,
  /\/etc\/passwd/,
  /\/fckeditor/,
  /\/ipython\/tree/,
  /\/irj\/go\//,
  /\/jkstatus$/,
  /\/jolokia/,
  /\/logfile/,
  /\/nginx.*conf$/,
  /\/tiny_?mce/,
  /\/umbraco/,
  /\/v[1-9]\/_catalog/,
  /^\/wp-(app|admin|config|contents?|includes|login|rss.*|register)/,
  /\/zimbra/,
  /%(2[26]|3([aA]|[dD])|5[cC]|7[cC])/, // note that the % is an encoded percent sign
  /%0[a-fA-F0-9]/,
  /%23/, // %23 = #
  /%2e%2e/, // a.k.a ..
  /%40/, // @ sign
  /%60/, // %60 = `
  /%7b/, // %7b = {
  /%ff/,
  /%uff0e/, // FULLWIDTH FULL STOP' (U+FF0E)
  /^.*%2$/,
  /^(\/(?!cgi-bin).*)[^/]+\.jsp/,
  /^(\/(?!cgi-bin).*)[^/]+\.php$/,
  /^(\/(?!cgi-bin).*)[^/]+\.sh/,
  /^(\/(?!cgi-bin).*)\?.{49,}$/, // excessively long URL parameters
  /^\/_search/,
  /^\/.login|^\/[Ww][eE][bB](dav|db|grind|mail|master|[Ss]ervice|shell|site|sql|stat|-INF)/,
  /^\/(heap)?[Dd]ump(\.rdb)?$/,
  /^\/(www|web)\....$/,
  /^\/[Tt]humb/,
  /^\/[Uu]pgrade(\/|\.)/,
  /^\/[Uu]pload/,
  /^\/[Uu]ser/,
  /^\/[Vv]agrant/,
  /^\/[Vv]ersion/,
  /^\/actuator/,
  /^\/admin\/includes/, // no includes
  /^\/admin$/,
  /^\/api\//,
  /^\/aspnet_client/,
  /^\/cluster\/list\.query$/,
  /^\/configprops$/,
  /^\/health$/,
  /^\/httptrace$/,
  /^\/liquibase$/,
  /^\/sling\/$/, // wrong decade, my friend
  /^\/tests\/phpunit_report\.xml$/,
  /^\/testweb$/,
  /^\/theme$/,
  /^\/themes$/,
  /^\/Thorfile$/,
  //  /^\/thread$/,
  //  /^\/threads$/,
  /^\/tiki\/doc\/stable\.version$/,
  //  /^\/tips$/,
  //  /^\/title$/,
  /^\/tmp/,
  /^\/TMP/,
  //  /^\/tn$/,
  /^\/TODO/,
  /^\/tools\/_backups\/$/,
  //  /^\/tools$/,
  //  /^\/top$/,
  //  /^\/topic$/,
  //  /^\/topics$/,
  /^\/Trace\.axd$/,
  /^\/trace$/,
  /^\/trackback$/,
  /^\/tradetheme$/,
  //  /^\/training$/,
  /^\/trans$/,
  /^\/transfer$/,
  //  /^\/travel$/,
  /^\/trivia\/$/,
  /^\/tst$/,
  /^\/tsweb\/$/,
  /^\/tsweb$/,
  //  /^\/tutorials$/,
  //  /^\/tv$/,
  /^\/txt\/$/,
  /^\/types$/,
  /^\/typo3/,
  /^\/uddi/,
  //  /^\/ui\/$/,
  //  /^\/ui$/,
  /^\/uk$/,
  /^\/unattend\.txt$/,
  /^\/UniversityServlet$/,
  /^\/UPDATE/,
  /^\/UPGRADE/,
  /^\/upstream_conf$/,
  /^\/uri$/,
  /^\/url$/,
  /^\/us$/,
  /^\/usage\/$/,
  /^\/usagedata\/$/,
  /^\/usebean\.jsp$/,
  /^\/usr-bin\/$/,
  /^\/usr\/$/,
  /^\/usuario/,
  /^\/utf8$/,
  /^\/utility_login\/$/,
  /^\/utils$/,
  /^\/uvpanel\/$/,
  //  /^\/v$/,
  /^\/v1/,
  /^\/var$/,
  /^\/variables\.1\.marketing\.adobe\.com\.txt$/,
  /^\/vb\./,
  /^\/vendor\//,
  /^\/VERSION/,
  /^\/view-source$/,
  /^\/vor[ou]d|^\/[Ww][Pp](\.*)?/,
  /^\/vpn\/$/,
  /^\/vtiger|^\/var\//,
  /^\/vtund\.conf$/,
  /^\/Warehouse/,
  /^\/wcx_ftp\.ini$/,
  /^\/web[.-]/,
  /^\/Web\.config$/,
  /^\/Webalizer\/$/,
  /^\/webmin\/$/,
  /^\/WebShell\.cgi$/,
  /^\/wenzhang$/,
  /^\/wiki/,
  /^\/Wishlist\.1\.marketing\.adobe\.com\.txt$/,
  /^\/WLDummyInitJVMIDs$/,
  /^\/ws\/v[1-9]/,
  /^\/WSsamples$/,
  /^\/wstats$/,
  /^\/wvdial\.conf$/,
  /^\/www-error\.log$/,
  /^\/www\.tar\.gz$/,
  /^\/wwwboard\/passwd\.txt$/,
  /^\/wwwstats\.htm$/,
  /^\/x[ms]l/,
  /^\/xferlog$/,
  /^\/xls\/$/,
  /^\/xphperrors\.log$/,
  /^\/xsql\/lib\/XSQLConfig\.xml$/,
  /^\/XSQLConfig\.xml$/,
  /^\/yaml_cron\.log$/,
  /^\/yaml\.log$/,
  /^\/yoneti/,
  /^\/yum\.log$/,
  /^\/zabbix\/$/,
  /^\/zebra\.conf/,
  /~/, // user Directory
  /applications\.pinpoint/,
  /build\.xml/,
  /debug\.xml/, // debug info
  /descriptorByName\/AuditTrailPlugin/,
  /G(runt|ulp|em)file\.(js|coffee|lock)/,
  /nohup\.out$/,
  /splunkd\/__raw/,
  /www\.[^/]+\.com/, // potential broken link
];
