/*
 * Copyright 2020 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
module.exports = [
  /.+\.axd/,
  /[()'"]/, // braces and escapes
  /[Tt]hank.*\.txt$/,
  /\/(.?php.*|tiki.*|test.*|user.*|wp-|ws|t.*|v.*|u.*|wiz.*|[Ww]eb)([aA]dmin|wiz.*)/,
  /\/[Ww][Ss]_/,
  /\/[Ww]ord[Pp]ress|\/WebSphere|\/wwwroot/,
  /\/\//, // double slashes
  /\/\/etc\//,
  /\/\.env/,
  /\/etc\/passwd/,
  /\/fckeditor/,
  /\/tiny_?mce/,
  /\/umbraco/,
  /\/wp-(app|admin|config|contents?|includes|login|rss.*|register)/,
  /\/zimbra/,
  /\.\./, // do not go a directory up
  /\.swf$/,
  /\/\.\./,
  /%(2[26]|3([aA]|[dD])|5[cC]|7[cC])/, // note that the % is an encoded percent sign
  /%2e%2e/, // a.k.a ..
  /%40/, // @ sign
  /%7b/, // %7b = {
  /%uff0e/, // FULLWIDTH FULL STOP' (U+FF0E)
  /^.*%2$/,
  /^(\/(?!cgi-bin).*)[^/]+\.php$/,
  /^(\/(?!cgi-bin).*)\?.{49,}$/, // excessively long URL parameters
  /^\/.login|^\/[Ww][eE][bB](dav|db|grind|mail|master|[Ss]ervice|shell|site|sql|stat|-INF)/,
  /^\/(www|web)\....$/,
  /^\/[Tt]humb/,
  /^\/[Uu]pdate([^-]|$)/,
  /^\/[Uu]pgrade/,
  /^\/[Uu]pload/,
  /^\/[Uu]ser/,
  /^\/[Vv]agrant/,
  /^\/[Vv]ersion/,
  /^\/admin\/includes/, // no includes
  /^\/sling\/$/, // wrong decade, my friend
  /^\/tests\/phpunit_report\.xml$/,
  /^\/testweb$/,
  /^\/theme$/,
  /^\/themes$/,
  /^\/Thorfile$/,
  /^\/thread$/,
  /^\/threads$/,
  /^\/tiki\/doc\/stable\.version$/,
  /^\/tips$/,
  /^\/title$/,
  /^\/tmp/,
  /^\/TMP/,
  /^\/tn$/,
  /^\/TODO/,
  /^\/tools\/_backups\/$/,
  /^\/tools$/,
  /^\/top$/,
  /^\/topic$/,
  /^\/topics$/,
  /^\/Trace\.axd$/,
  /^\/trace$/,
  /^\/trackback$/,
  /^\/tradetheme$/,
  /^\/training$/,
  /^\/trans$/,
  /^\/transfer$/,
  /^\/travel$/,
  /^\/trivia\/$/,
  /^\/tst$/,
  /^\/tsweb\/$/,
  /^\/tsweb$/,
  /^\/tutorials$/,
  /^\/tv$/,
  /^\/txt\/$/,
  /^\/types$/,
  /^\/typo3/,
  /^\/uddi/,
  /^\/ui\/$/,
  /^\/ui$/,
  /^\/uk$/,
  /^\/unattend\.txt$/,
  /^\/UniversityServlet$/,
  /^\/UPDATE/,
  /^\/UPGRADE/,
  /^\/upstream_conf$/,
  /^\/uri$/,
  /^\/url$/,
  /^\/us$/,
  /^\/usage\/$/,
  /^\/usagedata\/$/,
  /^\/usebean\.jsp$/,
  /^\/usr-bin\/$/,
  /^\/usr\/$/,
  /^\/usuario/,
  /^\/utf8$/,
  /^\/utility_login\/$/,
  /^\/utils$/,
  /^\/uvpanel\/$/,
  /^\/v$/,
  /^\/v1/,
  /^\/var$/,
  /^\/variables\.1\.marketing\.adobe\.com\.txt$/,
  /^\/vb\./,
  /^\/vendor\//,
  /^\/VERSION/,
  /^\/view-source$/,
  /^\/vor[ou]d|^\/[Ww][Pp](\.*)?/,
  /^\/vpn\/$/,
  /^\/vtiger|^\/var\//,
  /^\/vtund\.conf$/,
  /^\/Warehouse/,
  /^\/wcx_ftp\.ini$/,
  /^\/web[.-]/,
  /^\/Web\.config$/,
  /^\/Webalizer\/$/,
  /^\/webmin\/$/,
  /^\/WebShell\.cgi$/,
  /^\/wenzhang$/,
  /^\/wiki/,
  /^\/Wishlist\.1\.marketing\.adobe\.com\.txt$/,
  /^\/WLDummyInitJVMIDs$/,
  /^\/WSsamples$/,
  /^\/wstats$/,
  /^\/wvdial\.conf$/,
  /^\/www-error\.log$/,
  /^\/www\.tar\.gz$/,
  /^\/wwwboard\/passwd\.txt$/,
  /^\/wwwstats\.htm$/,
  /^\/x[ms]l/,
  /^\/xferlog$/,
  /^\/xls\/$/,
  /^\/xphperrors\.log$/,
  /^\/xsql\/lib\/XSQLConfig\.xml$/,
  /^\/XSQLConfig\.xml$/,
  /^\/yaml_cron\.log$/,
  /^\/yaml\.log$/,
  /^\/yoneti/,
  /^\/yum\.log$/,
  /^\/zabbix\/$/,
  /^\/zebra\.conf/,
  /~/, // user Directory
  /debug\.xml/, // debug info
  /www\.[^/]+\.com/, // potential broken link
];
